spring.application.name=prove-yourself
# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.show-sql=true
# DATASOURCE (Local Environment)
spring.datasource.url=jdbc:postgresql://localhost:5432/prove-yourself
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# DISABLE FLYWAY (UNTIL NEEDED)
spring.flyway.enabled=false
# DISABLE DOCKER COMPOSE (FOR NOW)
spring.docker.compose.enabled=false
# JWT CONFIGURATION
jwt.secret=${JWT_SECRET}
jwt.expiration=15
# Cookie CONFIGURATION
cookie.name=auth-token
cookie.http-only=true
cookie.secure=false
cookie.max-age=720
cookie.same-site=Lax
cookie.path=/
# LOGGING
#logging.level.org.springframework.security = DEBUG
# MULTIPART CONFIGURATION (LIMITING FILE UPLOAD SIZE)
spring.servlet.multipart.max-file-size=2MB
# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_ADDRESS}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true