spring.application.name=prove-yourself

# JPA Configuration
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.hibernate.show-sql = true

# DATASOURCE (Local Environment)
spring.datasource.url = jdbc:postgresql://localhost:5432/prove-yourself
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

# DISABLE FLYWAY (UNTIL NEEDED)
spring.flyway.enabled = false

# DISABLE DOCKER COMPOSE (FOR NOW)
spring.docker.compose.enabled = false

# OAUTH2 Configuration
# GITHUB
spring.security.oauth2.client.registration.github.client-id = ${CLIENT_ID_GITHUB}
spring.security.oauth2.client.registration.github.client-secret = ${CLIENT_SECRET_GITHUB}
spring.security.oauth2.client.registration.github.redirect-uri = http://localhost:8080/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.github.scope = profile,name

# GOOGLE
spring.security.oauth2.client.registration.google.client-id = ${CLIENT_ID_GOOGLE}
spring.security.oauth2.client.registration.google.client-secret = ${CLIENT_SECRET_GOOGLE}
spring.security.oauth2.client.registration.google.redirect-uri = http://localhost:8080/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope = profile,email

# LOGGING
#logging.level.org.springframework.security = DEBUG
# MULTIPART CONFIGURATION (LIMITING FILE UPLOAD SIZE)
spring.servlet.multipart.max-file-size=2MB

# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html